In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('data_for_project.csv')

In [3]:
df.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [11]:
# 1 
MAU = df['user_id'].unique()
MAU
#7639

array(['8c020470-8461-11ed-83d0-552e8cc749d6',
       '5875f070-7b92-11ee-a6fb-8b298e83f4f7',
       '3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6', ...,
       '39ec9130-4ae3-11ed-a969-7554db53449c',
       '39df47d0-67e5-11ee-8fb4-6fca0b38dcdb',
       '954bc9b0-5e75-11ed-b1a2-e10d23811e40'],
      shape=(7639,), dtype=object)

In [12]:
# 2
df['date'] = pd.to_datetime(df['date'])
DAU = df.groupby(df['date'].dt.date)['user_id'].nunique()
print("Средний DAU:", DAU.mean())

Средний DAU: 560.4666666666667

In [13]:
# 3
# Новые пользователи 1 ноября
new_users = df.loc[df['date'].dt.date == pd.to_datetime('2023-11-01').date(), 'user_id'].unique()

# Вернувшиеся 2 ноября
returned_users = df.loc[df['date'].dt.date == pd.to_datetime('2023-11-02').date(), 'user_id'].unique()

retention_day1 = len(set(returned_users) & set(new_users)) / len(new_users) * 100
print("Retention первого дня:", round(retention_day1, 1), "%")

Retention первого дня: 26.6 %

In [14]:
# 5 
conversion = df.loc[df['view_adverts'] > 0, 'user_id'].nunique() / df['user_id'].nunique() * 100
print("Конверсия в просмотр объявления:", round(conversion, 1), "%")

Конверсия в просмотр объявления: 46.3 %

In [20]:
# 6 
r = df['view_adverts'].sum()/len(df['user_id'].unique())
print(r)

2.8687000916350307

In [21]:
# 7 
promoters = 1200
detractors = 500
total = 2000
NPS = (promoters / total - detractors / total) * 100
print("NPS:", round(NPS, 1), "%")

NPS: 35.0 %

In [30]:
# 8
import pandas as pd
from scipy import stats
df = pd.read_csv("AB_test.csv")
df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [31]:
arpu = df.groupby(['experiment_num','experiment_group'])['revenue'].mean().reset_index()
print(arpu)

   experiment_num experiment_group     revenue
0               1          control  722.460215
1               1             test  665.739583
2               2          control  704.653763
3               2             test  332.929167
4               3          control  663.206452
5               3             test  998.668750

In [33]:
results = {}
for exp in df['experiment_num'].unique():
    test_group = df[(df['experiment_num']==exp) & (df['experiment_group']=='test')]['revenue']
    control_group = df[(df['experiment_num']==exp) & (df['experiment_group']=='control')]['revenue']
    
    t_stat, p_val = stats.ttest_ind(test_group, control_group, equal_var=False)
    results[exp] = {'t_stat': t_stat, 'p_value': p_val}

results

{np.int64(1): {'t_stat': np.float64(-0.40038217097094403),
  'p_value': np.float64(0.688966190624939)},
 np.int64(2): {'t_stat': np.float64(-3.270721407077585),
  'p_value': np.float64(0.0011282266247294027)},
 np.int64(3): {'t_stat': np.float64(1.8809791906941422),
  'p_value': np.float64(0.06031548002841902)}}

In [34]:
# lister
lister = pd.read_csv('lister.csv')
lister

     user_id        date  cnt_adverts  age  cnt_contacts  revenue
0        100  2022-01-01            6   21           119       53
1        100  2022-01-02            2   21           200       18
2        100  2022-01-03            6   21           193       42
3        100  2022-01-04            2   21           143       38
4        100  2022-01-05            2   21           190       40
..       ...         ...          ...  ...           ...      ...
153      130  2022-01-27            1   22           185       60
154      130  2022-01-19            0   22            86       41
155      130  2022-01-28            0   22           183        5
156      130  2022-01-30            0   22            86       12
157      130  2022-01-13            2   22            97       27

[158 rows x 6 columns]

In [61]:
dff = lister.groupby('user_id').count()
df1 = dff.reset_index()
count_users = df1['user_id'].count()
lister['revenue'].sum()/count_users

np.float64(156.48387096774192)

In [62]:
lister['age'].median()

28.0